# Monorepo #####################################################################

monorepo_root = true
[monorepo]
config_roots = ["pkgs/*"]

[tools]


# Stack ########################################################################

# Node.js
node = "lts"
pnpm = "latest"
